const stations = [
    { label: "Acolman", value: "aco" },
    { label: "Ajusco Medio", value: "ajm" },
    { label: "Atizapán", value: "ati" },
    { label: "Camarones", value: "cam" },
    { label: "Centro de Ciencias de la Atmósfera", value: "cca" },
    { label: "Chalco", value: "cho" },
    { label: "Cuajimalpa", value: "cua" },
    { label: "FES Acatlán", value: "fac" },
    { label: "Hospital General de México", value: "hgm" },
    { label: "Camarones", value: "inn" },
    { label: "Centro de Ciencias de la Atmósfera", value: "izt" },
    { label: "Laboratorio de Análisis Ambiental", value: "lla" },    
    { label: "La Presa", value: "lpr" },
    { label: "Merced", value: "mer" },
    { label: "Miguel Hidalgo", value: "mgh" },
    { label: "Montecillo", value: "mon" },
    { label: "Nezahualcóyotl", value: "nez" },
    { label: "Pedregal", value: "ped" }, 
    { label: "San Agustín", value: "sag" },
    { label: "Santa Fe", value: "sfe" },
    { label: "San Juan de Aragón", value: "sja" },
    { label: "Tláhuac", value: "tah" },
    { label: "Tlalnepantla", value: "tla" },
    { label: "Tultitlán", value: "tli" },
    { label: "UAM Xochimilco", value: "uax" },
    { label: "UAM Iztapalapa", value: "uiz" },
    { label: "Villa de las Flores", value: "vif" },
    { label: "Xalostoc", value: "xal" },
  ];

export default stations